Collections:
  - Name: Baseline
    Metadata:
      Training Data: Mini-ImageNet
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 1x V100 GPUs
    Paper: https://arxiv.org/abs/1904.04232
    README: configs/classification/baseline/README.md

Models:
  - Name: baseline_conv4_1xb64_mini-imagenet_5way-1shot
    Metadata:
      Training Data: Mini-ImageNet
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: none
    Weights: none
    Config: configs/classification/baseline/mini_imagenet/baseline_conv4_1xb64_mini-imagenet_5way-1shot.py
  - Name: baseline_conv4_1xb64_mini-imagenet_5way-5shot
    Metadata:
      Training Data: Mini-ImageNet
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: none
    Weights: none
    Config: configs/classification/baseline/mini_imagenet/baseline_conv4_1xb64_mini-imagenet_5way-5shot.py
  - Name: baseline_resnet12_1xb64_mini-imagenet_5way-1shot
    Metadata:
      Training Data: Mini-ImageNet
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: none
    Weights: none
    Config: configs/classification/baseline/mini_imagenet/baseline_resnet12_1xb64_mini-imagenet_5way-1shot.py
  - Name: baseline_resnet12_1xb64_mini-imagenet_5way-5shot
    Metadata:
      Training Data: Mini-ImageNet
      Epochs: 200
      Batch Size: 64
    In Collection: Baseline
    Results:
      - Task: Few Shot Image Classification
        Dataset: Mini-ImageNet
        Metrics:
          Accuracy: none
    Weights: none
    Config: configs/classification/baseline/mini_imagenet/baseline_resnet12_1xb64_mini-imagenet_5way-5shot.py
